### ISSUE TITLE
mysql5.7 Apple Silicon Support

### ISSUE THREAD

**Issue by sarbesh** [vbabak/docker-mysql-master-slave#5]
branch: [mysql5.7](https://github.com/vbabak/docker-mysql-master-slave/tree/mysql5.7) fails to start on Apple silicon as the image doesn't support arm architecture.
```
[+] Running 0/2
 ⠇ mysql_slave Pulling                                                                                                                               4.8s
 ⠿ mysql_master Error                                                                                                                                4.8s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

The following `platform: linux/x86_64`  has to be added for both master and slave in order to pull the correct image for Apple silicon

```
services:
  mysql_master:
    image: mysql:5.7
    platform: linux/x86_64
```

reference: https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8

**Comment by vbabak** [comment]
Also `export DOCKER_DEFAULT_PLATFORM=linux/amd64 `should help to enforce "linux/amd64" on Apple M1 chip.
